syntax = "proto3";
package com.staploy;

message Version {
  string versionName = 1;
  optional uint64 archiveSize = 2;
  optional bytes archiveHash = 3;

  repeated string entryBinaries = 4;
  repeated bytes entryBinariesHash = 5;
}

message AppInfo {
  string appName = 1;
  optional string appDescription = 2;
}

message AppInfoFetch {
  AppInfo app = 1;
  repeated Version appVersion = 2;
}

message InstalledAppInfo {
  AppInfo app = 1;
  optional Version currentVersion = 2;
  repeated Version availableVersion = 3;
}