syntax = "proto3";
package com.staploy;
import "app.proto";

enum ProtocolProcedure {
  PROCEDURE_SERVER_HELLO = 0;
  PROCEDURE_REQUEST_TASK = 1;
  PROCEDURE_CHECK_TASK = 2;
  PROCEDURE_CANCEL_TASK = 3;
}

enum ActionProcedure {
  PROCEDURE_NONE = 0;
  PROCEDURE_REQUEST_WORKER_INFO = 1;
  PROCEDURE_REQUEST_APP_INFO = 2;

  PROCEDURE_PUSH_APP_BINARY = 3; // Reserved, But no used by protobuf parser (Via http file request header)
  PROCEDURE_ADD_APP_VERSION = 4;
  PROCEDURE_SET_APP_VERSION = 5;
  PROCEDURE_DELETE_APP_VERSION = 6;
  PROCEDURE_EXECUTE_SHELL = 7;
}

enum CpuArch {
  i386 = 0;
  x86_64 = 1;
  arm = 2;
  aarch64 = 3;
  riscv32 = 4;
  riscv64 = 5;
  mipsel = 6;
  mips64el = 7;
}

message Packet {
  ProtocolProcedure procedure = 1;
  string challengeCode = 2;
  optional ActionProcedure actionProcedure = 3;
  optional bytes extraData = 4;
}

message ServerPacket {
  Packet packetInfo = 1;
  repeated AppInfoFetch appInfoFetch = 2;
}

message WorkerPacket {
  Packet packetInfo = 1;
  optional Result taskResult = 2;
  optional WorkerInfo workerInfo = 3;
}

message WorkerInfo {
  string workerId = 1;

  optional CpuArch cpuArch = 2;
  optional string binLocation = 3;
  optional sint64 cpuCoreCount = 4;
  optional sint64 memoryInBytes = 5;

  repeated InstalledAppInfo installedApp = 6;
}

message Result {
  bool taskStarted = 1;
  bool resultFinished = 2;
  bool resultSuccessful = 3;
  optional int32 errorCode = 4;
  optional string errorMessage = 5;
}